version: '2.1'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4576:4576"
      - "8080:8080"
    environment:
      - SERVICES=version: "3.7"

services:
  localstack:
    container_name: myservice_localstack
    image: localstack/localstack:latest
    ports:
      # Expose in a different port to avoid collisions
      - "44566:4566"
    volumes:
        # Use the current directory as the entry point 
      # for additional configs
      - './:/docker-entrypoint-initaws.d'

volumes:
  data-volume: