service: gitlab-example
provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: src/index.handler
    events:
      - http: GET hello

plugins:
  - serverless-localstack


custom:
  localstack:
     stages:
       - local